name: mm
channels:
  - conda-forge
dependencies:
  - aiobotocore=2.14.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py311h05b510d_0
  - aioitertools=0.11.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.26=h1e647a1_2
  - aws-c-cal=0.7.4=h41e72e7_0
  - aws-c-common=0.9.27=h99b78c6_0
  - aws-c-compression=0.2.19=h41e72e7_0
  - aws-c-event-stream=0.4.3=h79ff00d_0
  - aws-c-http=0.8.8=h69517e7_1
  - aws-c-io=0.14.18=h20e6805_7
  - aws-c-mqtt=0.10.4=h3e8bf47_18
  - aws-c-s3=0.6.4=he4d1bc2_11
  - aws-c-sdkutils=0.1.19=h85401af_2
  - aws-checksums=0.1.18=h85401af_10
  - aws-crt-cpp=0.28.2=h46cb957_0
  - aws-sdk-cpp=1.11.379=h8d911dc_8
  - azure-core-cpp=1.13.0=hd01fc5c_0
  - azure-identity-cpp=1.8.0=h13ea094_2
  - azure-storage-blobs-cpp=12.12.0=hfde595f_0
  - azure-storage-common-cpp=12.7.0=hcf3b6fd_1
  - azure-storage-files-datalake-cpp=12.11.0=h082e32e_1
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=h5499902_0
  - bokeh=3.5.2=pyhd8ed1ab_0
  - boto3=1.35.7=pyhd8ed1ab_0
  - botocore=1.35.7=pyge310_1234567_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py311h3f08180_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.33.1=hd74edd7_0
  - ca-certificates=2024.8.30=hf0a4a13_0
  - cachier=3.0.1=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cf_xarray=0.9.5=pyhd8ed1ab_1
  - cffi=1.17.0=py311h3a79f62_1
  - cftime=1.6.4=py311h5d790af_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - contourpy=1.3.0=py311h2c37856_0
  - copernicusmarine=1.3.3=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py311h05b510d_0
  - dask=2024.8.2=pyhd8ed1ab_0
  - dask-core=2024.8.2=pyhd8ed1ab_0
  - dask-expr=1.1.12=pyhd8ed1ab_0
  - distributed=2024.8.2=pyhd8ed1ab_0
  - dnspython=2.6.1=pyhd8ed1ab_1
  - esmf=8.6.1=nompi_hb829c31_3
  - esmpy=8.6.1=pyhc1e730c_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fonttools=4.53.1=py311h460d6c5_1
  - freetype=2.12.1=hadb7bae_2
  - frozenlist=1.4.1=py311h05b510d_0
  - fsspec=2024.6.1=pyhff2d567_0
  - geojson=3.1.0=pyhd8ed1ab_0
  - geos=3.12.2=h00cdb27_1
  - gflags=2.2.2=hc88da5d_1004
  - glog=0.7.1=heb240a5_0
  - gsw=3.6.19=py311h5d790af_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=nompi_hec07895_105
  - holoviews=1.19.1=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hvplot=0.10.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.8=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intake=2.0.6=pyhd8ed1ab_0
  - intake-xarray=0.7.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_h00cdb27_1
  - libaec=1.1.3=hebf3989_0
  - libarrow=17.0.0=h20538ec_13_cpu
  - libarrow-acero=17.0.0=hf9b8971_13_cpu
  - libarrow-dataset=17.0.0=hf9b8971_13_cpu
  - libarrow-substrait=17.0.0=hbf8b706_13_cpu
  - libblas=3.9.0=23_osxarm64_openblas
  - libboost=1.86.0=h610977f_1
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=23_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.9.1=hfd8ffcc_0
  - libcxx=18.1.8=h3ed4263_6
  - libdeflate=1.21=h99b78c6_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.28.0=hfe08963_0
  - libgoogle-cloud-storage=2.28.0=h1466eeb_0
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=23_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libnetcdf=4.9.2=nompi_he469be0_114
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h517c56d_1
  - libparquet=17.0.0=hf0ba9ef_13_cpu
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.20.0=h64651cc_1
  - libtiff=4.6.0=hf8409c0_4
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.16=hc9fafa5_1
  - libxml2=2.12.7=h9a80f22_3
  - libxslt=1.1.39=h223e5b9_0
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.3.1=hfb2fe0b_1
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - llvm-openmp=18.1.8=hde57baf_1
  - llvmlite=0.43.0=py311hc367efa_1
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.2=py311h267d04e_2
  - lxml=5.3.0=py311hd29ea9b_0
  - lz4=4.3.3=py311hebe0b09_1
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h460d6c5_1
  - matplotlib-base=3.9.2=py311hbe3227e_1
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py311h6bde47b_0
  - multidict=6.0.5=py311he2be06e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf-fortran=4.6.1=nompi_hb210b0d_106
  - netcdf4=1.7.1=nompi_py311h42682c7_101
  - networkx=3.3=pyhd8ed1ab_1
  - numba=0.60.0=py311h9506ed5_0
  - numcodecs=0.13.0=py311h4b4568b_0
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.2=h8359307_0
  - orc=2.0.2=h75dedd0_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311h4b4568b_1
  - panel=1.5.0=pyhd8ed1ab_0
  - param=2.1.1=pyhff2d567_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=10.4.0=py311hd7951ec_0
  - pip=24.2=pyh8b19718_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.24.0=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - portalocker=2.10.1=py311h267d04e_0
  - psutil=6.0.0=py311hd3f4193_0
  - pthread-stubs=0.4=h27ca646_1001
  - pyarrow=17.0.0=py311h35c05fe_1
  - pyarrow-core=17.0.0=py311he42f270_1_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyinterp=2024.6.0=py311hb488336_101
  - pymongo=4.8.0=py311h3f08180_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pystac=1.10.1=pyhd8ed1ab_0
  - pystac-client=0.8.3=pyhd8ed1ab_0
  - pytest=8.3.2=pyhd8ed1ab_0
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyviz_comms=3.0.3=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311hd3f4193_0
  - qhull=2020.2=h420ef59_5
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - requests=2.32.3=pyhd8ed1ab_0
  - s3fs=2024.6.1=pyhd8ed1ab_0
  - s3transfer=0.10.2=pyhd8ed1ab_0
  - scipy=1.14.1=py311h2929bc6_0
  - semver=3.0.2=pyhd8ed1ab_0
  - setuptools=72.2.0=pyhd8ed1ab_0
  - shapely=2.0.6=py311he141ab1_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=hd02b534_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sparse=0.15.4=pyhd8ed1ab_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py311h460d6c5_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - watchdog=5.0.0=py311h460d6c5_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py311h460d6c5_1
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xesmf=0.8.7=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.7=py311h460d6c5_0
  - zarr=2.18.2=pyhd8ed1ab_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.3.1=hfb2fe0b_1
  - zstandard=0.23.0=py311h4a6b76e_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - arrow==1.3.0
      - dbdreader==0.5.7
      - gliderflight==1.2.0
      - glidernetcdf==0.0.2
      - glidersim==0.3.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - latlon==0.2.0
      - mamma-mia==0.1.0
      - referencing==0.35.1
      - rpds-py==0.20.0
      - stac-validator==3.3.2
      - types-python-dateutil==2.9.0.20240821
      - utm==0.7.0
