name: mm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - loguru=0.7.2
  - pyinterp=2024.6.0
  - xarray=2024.7.0
  - yaml=0.2.5
  - zarr=2.18.2
  - plotly=5.24.0
  - intake=2.0.6
  - intake-xarray=0.7.0
  - copernicusmarine=1.3.3
  - xesmf=0.8.7
  - s3fs=2024.6.1
