name: mm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - loguru
  - pyinterp
  - xarray
  - yaml
  - zarr
  - plotly
  - intake
  - intake-xarray
  - copernicusmarine
  - xesmf
  - s3fs
prefix: /home/thopri/miniforge3/envs/mm
