name: mm
channels:
  - conda-forge
dependencies:
  - copernicusmarine
  - geojson
  - numpy
  - plotly
  - pyinterp
  - pytest
  - python=3.11
  - zarr
  - gsw
prefix: /usr/local/Caskroom/miniforge/base/envs/mm
