name: mm
channels:
  - conda-forge
dependencies:
  - geojson
  - numpy
  - plotly
  - pyinterp
  - pytest
  - python=3.11
  - zarr
  - gsw
  - copernicusmarine
  - intake
  - intake-xarray
  - s3fs
  - loguru
  - xesmf
prefix: /usr/local/Caskroom/miniforge/base/envs/mm
