project:
  type: website
  output-dir: ../docs

website:
  title: "Mamma Mia Documentation"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    logo: mammamia_logo.png
    search: true
    style: docked
    background: '#00B5FF'
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Installation"
        href: installation.qmd
      - text: "Mamma Mia"
        href: mamma-mia.qmd
      - text: "Simulators"
        href: simulators.qmd
      - text: "About"
        href: about.qmd
      - text: "Acknowledgments"
        href: acknowledgement.qmd
    tools:
      - href: https://github.com/NOC-MDP/MammaMia
        icon: github
  page-footer: "Copyright 2025 National Oceanography Centre"
  repo-url: https://github.com/NOC-MDP/MammaMia
  repo-actions: [issue]
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

