project:
  type: website
  output-dir: ../docs

website:
  title: "Mamma Mia Documentation"
  sidebar:
    logo: mammamia_logo.png
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Mamma Mia"
        href: mamma-mia.qmd
      - section: "Simulators"
        href: simulators.qmd
      - text: "About"
        href: about.qmd
      - text: "Acknowledgments"
        href: acknowledgement.qmd
    tools:
      - href: https://github.com/NOC-MDP/MammaMia
        icon: github
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

