title: Mamma Mia
description: Toolbox to simulate payloads collected by ocean platforms
remote_theme: NOC-MDP/jekyll-theme-rtd

# Theme settings:
site_author: thopri
repo_url: "https://github.com/NOC-MDP/MammaMia"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist